datasource:
  springbatch:
    jdbc-url: jdbc:postgresql://10.10.100.100:5432/postgres
    username: postgres
    password: Azerty123!
  lepto:
    jdbc-url: jdbc:oracle:thin:@//lepto.unc.prod:1521/gestdev.lepto
    username: grhum
    password: clement
    driver-class-name: oracle.jdbc.OracleDriver
  parcoursup:
    jdbc-url: jdbc:postgresql://10.10.100.100:5432/parcoursup
    username: parsup_usr
    password: parsup_usr
    hibernate-hbm2ddl-auto: create-drop
file:
  local-tmp-file: C:/temp/tmpInputFile.csv
  archive-directory: C:/temp/
spring:
  batch:
    initialize-schema: always
    job.enabled: false
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR   
 
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#        jdbc.lob.non_contextual_creation: true
#    show-sql: true